### ISSUE TITLE
Crash on startup with fabric mod loader 0.12.1

### ISSUE THREAD

**Issue by SplendidAlakey** [The-Fireplace-Minecraft-Mods/Fireplace-Lib#35]
**Describe the bug**

The game crashes on initialization when FirepalceLib is present in the mods folder and fabric mod loader 0.12.1 is used. The issue doesn't happen with mod loader 0.11.7.

**To Reproduce**

1. Install fabric mod loader 0.12.1
2. Install fabric API 0.40.8
3. Install Fireplace-Lib-6.0.6+1.17.1
4. Launch the game

**Logs/Screenshots/Videos**

[removed]

**Versions (please complete the following information, do *NOT* say "latest"):**

 - Minecraft: 1.17.1
 - Mod Version: Fireplace-Lib-6.0.6+1.17.1
 - Fabric API: fabric-api-0.40.8+1.17

**Comment by The-Fireplace** [comment]
Fabric Loader 0.12 is currently in Beta, and apparently has extra steps to set up because it is in beta. Once it is stable, I will update Fireplace Lib to require it. Until then, you can install Annotated DI 2.0.4 alongside Fireplace Lib and the crashing should stop.
https://www.curseforge.com/minecraft/mc-mods/annotated-di
